version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "submodule"
    directory: "/"
    schedule:
      interval: "daily"
