name: Release All-in-One

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this workflow.
  push:
    paths-ignore:
      - '**/*.md'
  # Run on PRs except for documentation
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
  IMAGE_NAME: funkwhale-aio
  PUSH_IMAGE: ${{ github.ref == 'refs/heads/main' }}
  BUILD_RELEASE: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get latest tagged release
        run: |
          cd funkwhale
          git fetch --tags
          LATEST_TAG_REV=$(git rev-list --tags --max-count 1)
          FUNKWHALE_RELEASE=$(git describe --tags ${LATEST_TAG_REV})
          echo "FUNKWHALE_REVISION=${LATEST_TAG_REV}" >> $GITHUB_ENV
          echo "FUNKWHALE_RELEASE=${FUNKWHALE_RELEASE}" >> $GITHUB_ENV
          git checkout ${FUNKWHALE_RELEASE}

      - name: Check whether latest release needs building
        if: ${{ env.PUSH_IMAGE }}
        run: |
          # Check whether there already is a Docker image for the current tag
          SERVER_TAGS=$(curl -s https://registry.hub.docker.com/v1/repositories/florianpiesche/funkwhale/tags | jq -r ".[].name") || SERVER_TAGS="none"
          for tag in ${SERVER_TAGS[@]}; do
            if [[ "$tag" == "${FUNKWHALE_RELEASE}" ]]; then
              echo "Release ${tag} has already been built."
              echo "BUILD_RELEASE=false" >> $GITHUB_ENV
              break
            fi
          done

      - name: Docker Setup QEMU
        if: ${{ env.PUSH_IMAGE && env.BUILD_RELEASE }}
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        if: ${{ env.PUSH_IMAGE && env.BUILD_RELEASE }}
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ env.PUSH_IMAGE && env.BUILD_RELEASE }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ env.PUSH_IMAGE && env.BUILD_RELEASE }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Prepare all-in-one build space
        if: ${{ env.BUILD_RELEASE }}
        run: |
          cd docker-funkwhale
          ./scripts/download-artifact.sh src/ ${{ env.FUNKWHALE_RELEASE }} build_front
          ./scripts/download-artifact.sh src/ ${{ env.FUNKWHALE_RELEASE }} build_api
          ./scripts/download-nginx-template.sh src/ ${{ env.FUNKWHALE_RELEASE }}

      - name: Copy modified Dockerfile into all-in-one buildspace
        run: |
          rm ./docker-funkwhale/Dockerfile
          cp ./Dockerfile ./docker-funkwhale/Dockerfile

      - name: Build and push ${{ env.IMAGE_NAME }} Docker image
        if: ${{ env.BUILD_RELEASE }}
        uses: docker/build-push-action@v2
        with:
          build-args: |
            FUNKWHALE_VERSION=${{ env.FUNKWHALE_RELEASE }}
            FUNKWHALE_REVISION=${{ env.FUNKWHALE_REVISION }}
          context: docker-funkwhale/
          file: docker-funkwhale/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.FUNKWHALE_RELEASE }}
            ghcr.io/${{ github.repo_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repo_owner }}/${{ env.IMAGE_NAME }}:${{ env.FUNKWHALE_RELEASE }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH_IMAGE }}
